---
title: "FinTech at First Glance"
author: "Tony Kuo"
date: "January 26, 2016"
output: 
  slidy_presentation
---

## Agenda

- From Application's Point of View
- Insurance X Biotech
- Big-Data Credit Scoring
- 新版個人資料保護法
- P2P貸款

## From Application's Point of View

- P2P Lending
- Virtual Currency
- Third-Party Payment
- Crowd Funding
- P2P Exchange
- Personal Finance

## P2P Lending
- Leading Players
    - [Lending Club](https://www.lendingclub.com/)
    - [陸金所LU.com](https://www.lu.com)

- Business Model
  1. Borrower posts lending requests
  2. Lender searches requests
  3. Lending through platform
  4. Paying back through platform

- Competitive Advantages
    - Peer to peer technology
    - Match making
    - Risk management

- Data
    - Customer profile
        - Lender
        - Borrower
    - Session log
        - Lender's searching behavior
        - Borrower's posting behavior

## P2P Lending X SAS

- What does it mean to SAS?
    - The market of **credit scoring** solution is expanding from banking/insurance only to these FinTech players.

- How SAS can make use of these FinTech to support for the client?
    - Credit risk data models
    - Credit scoring solutions
    - Model management
    - Decision hub to aid match making
    - Marketing automation to send customized messages to lenders/borrowers

- What would be the challenges to SAS if we need to do for the above bullet?
    - The target audience might not have banking/JCIC data which current data models for banking might not be suitable
    - Can our solution make quicker and more accurate match making/pushes than current adoption?

## Virtual Currency

- Leading Players
    - [Bit Coin](https://bitcoin.org)
    - WoW Token
    - Linden Dollar

- Business Model
  1. Mining or purchasing for coins
  2. Saving in e-wallets
  3. Transaction

- I personally do not think SAS could involve in this area.

## Third-Party Payment

- Leading Players
    - [PayPal](https://www.paypal.com)
    - [AliPay](https://www.alipay.com)

- Business Model
  1. Buyer pays platform
  2. Platform sends notice to seller
  3. Seller sends product to buyer
  4. Hesitation period
  5. Platform pays seller

- Competitive Advantages
    - Payment/Capital management
    - Guarantee for both buyers/sellers
    - Low commission

- Data
    - Customer Profile
        - Seller
        - Buyer
    - Session Log
        - Buyer's searching behavior
        - Seller's posting behavior

## Third-Party Payment X SAS

- What does it mean to SAS?
    - The market of **small business** solution is expanding.

- How SAS can make use of these FinTech to support for the client?
    - Credit data models for online business
    - Credit scoring solutions, how to value the credit score of a small business?
    - Credit scoring solutions, how to value a buyer's credit score?
    - Marketing automation to send customized messages to buyers/sellers

- What would be the challenges to SAS if we need to do for the above bullet?
    - Do we have credit data models for small business?

## Crowd Funding

- Leading Players
    - [Kickstarter](https://www.kickstarter.com)
    - [FlyingV](https://www.flyingv.cc)

- Business Model
  1. Fund raiser posts funding project with a target
  2. Supporter donates
  3. Reaches target
  4. Supporter gets commodity/service/stock as return

- I personally do not think SAS could involve in this area.

## P2P Exchange

- Leading Players
    - [TransferWise](https://transferwise.com)
    - [Azimo](https://azimo.com/en/)

- Business Model
  1. Saving Euros in exchange for Pounds
  2. Match-making
  3. Saving Pounds in exchange for Euros

- Competitive Advantages
    - Low commission comparing to banks
    - Peer to peer technology
    - Match-making

- Data
    - Customer Profile
    - Session Log
    - Transaction Log

## P2P Exchange X SAS

- What does it mean to SAS?
    - We can leverage solutions like **CLA**, **AML**, and **Fraud**

- How SAS can make use of these FinTech to support for the client?
    - **Customer Link Analysis**
    - **Anti-Money Laundering**
    - **Fraud Detection**

- What would be the challenges to SAS if we need to do for the above bullet?
    - How to propose the value of **CLA**?
    - How to propose the value of **AML** and **Fraud** prior to regulations?
  
## Personal Finance

- Leading Players
    - [Wealthfront](https://www.wealthfront.com)
    - [Mint](https://www.mint.com)

- Business Model
  1. Customer registers with profile, risk appetite, and portfolio data
  2. Artificial Intelligence/Machine Learning algorithm
  3. Advisory dashboard

- Competitive Advantages
    - Algorithm
    - Low commission
    - Human advisory is also available

- Data
    - Customer profile
    - Session log

## Personal Finance X SAS

- What does it mean to SAS?
    -  **Portfolio management** might be a future battlefield for IT vendors

- How SAS can make use of these FinTech to support for the client?
    - Market risk data models
    - Portfolio management, Optimization solutions
    - Visualization

- What would be the challenges to SAS if we need to do for the above bullet?
    - Do we have market risk data models for individual investors?
    - Do we have APIs for **Optimization** and **Visualization**?

## Insurance X Biotech

- Example
    - [Zhongan Insurance](zhongan.com)

- Competitive Advantages
    - Using mobile phone and plug-in to manage blood glucose
    - Incentives for users who keep blood glucose level at normal
    - Push analysis report to users

- Data
    - Customer profile
      - Especially blood glucose
    - Session log

## Biotech X SAS

- What does it mean to SAS?
    - **Plug-ins** for mobile phone and **Sports Band** can generate a great amount of physical data of users

- How SAS can make use of these FinTech to support for the client?
    - **Health scoring** for insurance companies and FinTech players
    - Training advise pushed through marketing automation solutions

- What would be the challenges to SAS if we need to do for the above bullet?
    - How to build a health scoring model based on data collected from **Plug-ins** for mobile phone and **Sports Band**?

## Big-Data Credit Scoring

- Stage 1
    - Platform data
        - Session log
- Stage 2
    - External data
        - E-commerce transaction
	      - Payment platform transaction
	      - Social network
- Stage 3
    - Financial Instruments
        - Banking
	      - Stock
	      - Insurance
- Stage 4
    - Government Open Data
        - Tax
	      - Traffic
	      - Mass Transportation
	      - Custom
- Stage 5
    - One Ultimate Credit System
    
## 新版個人資料保護法

- 目前僅有金管會針對金控提出了金融控股公司子公司間共同行銷管理辦法，並沒有機關針對集團企業子公司共同行銷提出管理辦法

- Original: 電腦處理個人資料保護法
	
	- 只規範電子資料
	- 8類行業、13個特定事業須遵守

- New: 個人資料保護法
	
	- 電子資料、紙本資料皆須遵守
	- 任何人/機關團體皆須遵守
	- 依循國際個資保護原則
	
## 個人資料的範疇

- 姓名、出生年月日、身分證統一編號、護照號碼、特徵、指紋、婚姻、家庭、教育、職業、**病歷**、**醫療**、**基因**、**性生活**、**健康檢查**、**犯罪前科**、聯絡方式、財務情況、社會活動、其他可以直接或間接識別該個人的資料
- 有關**病歷**、**醫療**、**基因**、**性生活**、**健康檢查**、**犯罪前科**不得蒐集、處理或應用
- 除非法律明文規定
- 執行法定職務
- 當事人自行公開
- 公務機關或學術研究機構為維護公共利益

## 非公務機關蒐集、處理個人資料要件

- 法律明文規定 or
- 與當事人有契約或類似契約關係 or
- 當事人自行公開或其他已合法公開的個人資料 or
- 學術研究機構基於公共利益，有必要做為統計或學術研究之用，且資料處理後無從識別特定的當事人 or
- 經當事人書面同意 or
- 與公共利益有關 or
- 取自於一般可得的來源

## 新增**告知**義務

- 無論直接或間接蒐集個人資料，須在使用前或首次使用時明確告知:
- 個人資料來源
- 蒐集者的名稱
- 蒐集的目的
- 個人資料的類別
- 個人資料利用的期間、地區、對象及方式
- 個資當事人擁有的權利

## 違反個資法的罰則

- 民事責任
	- 每人每事500-20,000
	- 同一件事最高200,000,000
- 刑事責任
	- 2年以下有期徒刑、拘役或併科200,000以下罰金(不具營利意圖)
	- 意圖營利可加重5年以下有期徒刑、得併科1,000,000以下罰金
- 行政處罰
	- 可處50,000-500,000罰金

## 金控業面臨新版個人資料保護法的解決方向

- 透過契約約定
- 以保險方式

## P2P貸款

- 根據國際證監會組織（IOSCO）的報告，全球P2P貸款業務在2013年已達60億美元，呈現90%的成長趨勢
- P2P貸款模式首創英國
- 其業務模式可以追溯到最早的個人互助借貸模式，類似台灣的**標會**或**互助會**
- 在美國，借款人在P2P貸款網站註冊時，只需要提供下列資訊就可以進行信用評等
	- 美國合法公民身份證明
	- 擁有超過520分的個人信用評分記錄
	- 個人財務情況
	
## P2P貸款運作模式

- Zopa(UK)
	- Zopa是P2P貸款的先鋒，該公司於2005年3月在倫敦成立，目前有50萬會員，已完成近5億英鎊的貸款，是歐洲最大的P2P貸款公司
	- 有錢可供出借的人在網路上列出**金額**、**利率**和**想要出借的時間**
	- 需要資金的人也可以比較各個貸款產品與自身的信用等級是否符合，確定適合自己的方案
- Prosper(US)
	- 成立於2006年，擁有超過200萬會員與超過6億美元的借貸金額，是目前世界上會員數最多的P2P貸款平台
	- Prosper利用線上拍賣機制對貸款進行競價拍賣
	- 借款人在Prosper網站輸入要借貸的金額，通常是小額，以不超過 3.5萬美元為限，與所能接受的貸款利率加上自己的信用評等
	- 有錢可供出借的人則可以尋找自己中意的金額與利率，同時參考借貸者的信用，再以自己願意提供的金額和利率競標，利率最低者將會得標
	- 在金融海嘯中違約率升高，Prosper在2009年變更業務模式，客戶的信用評等與貸款利率改由Prosper的風險評量系統來決定，並剔除許多信用不佳的借款人，以保護資金出借人
- Lending Club(US)
	- 成立於2007年，現在是全球借貸金額最大的P2P貸款公司，已完成39億美元的貸款
	- 借款人最高可借3.5萬美元，在輸入其貸款金額與個人資料後，Lending Club可從徵信體系拿到借款人的信用記錄，加上借款人的所得資料，計算出借款人可能的違約機率，再根據此風險決定其利率
	- 允許信用優秀的借款人拿到比銀行更低的利率，而信用不良的借款人在支付更高利率的前提下也能得到貸款
	- 也提供企業貸款，貸款額度從1.5萬美元到10萬美元不等，利率從5.9%到29.9%不等，視乎借款公司的信用狀況而定
- Others
	- Auxmoney(DE)
	- Aqush(JP)
	- popfunding(KR)
	- Comunitae(ES)
	- Uppspretta(IS)
	- Fairplace(BR)
	- 人人貸與拍拍貸(CN)

## 短時間內發展蓬勃之主要原因

- 本質上屬於民間信用借貸，與傳統銀行貸款相比手續簡便、門檻低
- 為借貸雙方提供從信息發佈、資料審核到轉帳借款、利率計算、按期還款的**一站式服務**
- 借錢者可比較每個借款人的利率與風險，把一筆錢打散分借給多個高風險高利率與低風險低利率的借款人，建立自己的portfolio
- 相對較高的年收益，承諾的年平均收益率都在5.5%-20％，再扣除P2P 貸款公司的手續費(通常是1%)與預期壞帳損失(一般在3%以下)
- P2P貸款公司只提供借錢者與借款人雙方的撮合平台，借錢者要自負違約風險
- P2P貸款公司的核心競爭力是建設一個完善且精準的P2P貸款信用評等系統
- P2P貸款公司不能對貸款提供擔保，也不能吸收出借人資金，也不得吸收公眾存款，否則需有銀行執照並受銀行法規範

## 銀行因應之道

- P2P貸款借款人通常是中低收入階層或剛出社會的年輕族群，一般銀行通常不願借貸
- 成立獨立的P2P貸款部門或子公司模式，進軍市場
	- 招商銀行在其**小企業e家**提供P2P貸款服務
	- 平安集團轉投資**陸金所**提供P2P貸款服務